version: "3"

services:
  centos:
    build: ./centos
    container_name: rest-container
    ports:
      - "8080:8080"
    volumes:
      - ./gradle-project:/gradle-project
    links:
      - mysql
    depends_on:
      - mysql
    privileged: true
    tty: true

  mysql:
    image: mysql:5.7
    container_name: rest-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/settings:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: rest
      MYSQL_USER: rest
      MYSQL_PASSWORD: rest
      MYSQL_ROOT_PASSWORD: rest

